# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - 5522:5432
    volumes:
      - ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql